[features]
seeds = false
[programs.devnet]
myepicproject = "6nS7aKfbY3WShCbxYc25NDU74A7S1MMkA99eyfaejJCX"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/pavlos/.config/solana/id.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
